# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
  main@v1:
    root: ./openapi/openapi.yaml
rules:
  no-unused-components: warn
theme:
  openapi:
    htmlTemplate: ./docs/index.html
    theme:
      colors:
        primary:
          main: "#32329f"
    generateCodeSamples:
      languages:  # Array of language config objects; indicates in which languages to generate code samples.
        - lang: curl # Can be one of the following supported languages: "curl", "Node.js", "JavaScript".
        - lang: "Node.js"
        - lang: "JavaScript"
