openapi: 3.1.0
info:
  version: 2.0.0-alpha
  title: Open Course Catalogue API
  termsOfService: ''
  contact:
    email: api.support@uni-foundation.eu
    url: 'https://github.com/EuropeanUniversityFoundation/occapi-openapi'
  # license:
  #   name: Apache 2.0
  #   url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://uni-foundation.eu/wp-content/uploads/2019/04/EUF-1.png'
  description:
    $ref: ./v2/info-description.md
tags:
  - name: API server
    description: Information about the server.
  - name: Institution
    description: Information about the Institutions covered by the server.
  - name: Organisational Unit
    description: Information about Organisational Units in an Institution.
  - name: Programme
    description: Information about Programmes offered by an Institution.
  - name: Course
    description: |
      Information about Courses offered by an Institution.

      _Course_ resources include a JSON:API _meta_ object containing information
       about the relation between each Course and specific Programmes.
  - name: Course instance
    description: |
      Information about instances of Courses offered by an Institution.

      _Course instance_ resources are directly linked to _Course_ resources.
servers:
  - url: '/occapi/v2'
    description: Sandbox server (example data)
paths:
  /:
    $ref: v2/paths/root.yaml
  # Institution & Organisational Unit endpoints.
  /hei:
    $ref: v2/paths/hei.yaml
  '/hei/{heiId}':
    $ref: 'v2/paths/hei@{heiId}.yaml'
  '/hei/{heiId}/ounit':
    $ref: 'v2/paths/ounit.yaml'
  '/hei/{heiId}/ounit/{id}':
    $ref: 'v2/paths/ounit@{id}.yaml'
  # Programme endpoints.
  '/hei/{heiId}/programme':
    $ref: 'v2/paths/programme.yaml'
  '/hei/{heiId}/ounit/{id}/programme':
    $ref: 'v2/paths/ounit@{id}-programme.yaml'
  '/hei/{heiId}/programme/{id}':
    $ref: 'v2/paths/programme@{id}.yaml'
  # Course endpoints.
  '/hei/{heiId}/course':
    $ref: 'v2/paths/course.yaml'
  '/hei/{heiId}/ounit/{id}/course':
    $ref: 'v2/paths/ounit@{id}-course.yaml'
  '/hei/{heiId}/programme/{id}/course':
    $ref: 'v2/paths/programme@{id}-course.yaml'
  '/hei/{heiId}/course/{id}':
    $ref: 'v2/paths/course@{id}.yaml'
  # Course instance endpoints.
  '/hei/{heiId}/course/{id}/instance':
    $ref: 'v2/paths/course@{id}-instance.yaml'
  '/hei/{heiId}/instance/{id}':
    $ref: 'v2/paths/instance@{id}.yaml'
